import { Inject, Logger, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import fs from 'fs';
import path from 'path';
import { I18nextModuleOptions } from './nestjs-i18next';
import { MODULE_OPTIONS_TOKEN } from './nestjs-i18next.module-definition';

export class I18nextJsonLoader implements OnModuleInit, OnModuleDestroy {
	private readonly logger = new Logger(I18nextJsonLoader.name);

	private watcher: fs.FSWatcher | null = null;
	private watchTimeout: NodeJS.Timeout | null = null;

	constructor(@Inject(MODULE_OPTIONS_TOKEN) protected readonly options: I18nextModuleOptions) {}

	onModuleInit() {
		if (this.options.loadingOptions.watch) {
			this.startWatcher();
		}
	}

	onModuleDestroy() {
		this.watcher?.close();
		if (this.watchTimeout) clearTimeout(this.watchTimeout);
	}

	private onRefreshCb?: () => void;

	public onChange(cb: () => void) {
		this.logger.debug('Watch file changes');

		this.onRefreshCb = cb;
	}

	private startWatcher() {
		const targetPath = path.resolve(process.cwd(), this.options.loadingOptions.path);

		try {
			this.watcher = fs.watch(targetPath, { recursive: true }, (eventType, filename) => {
				if (filename && filename.endsWith('.json')) {
					if (this.watchTimeout) clearTimeout(this.watchTimeout);

					this.watchTimeout = setTimeout(() => {
						if (this.options.logging) {
							this.logger.log(
								`Translation file changed. Checking translation changes...`
							);
						}

						if (this.onRefreshCb) this.onRefreshCb();
						this.watchTimeout = null;
					}, 100);
				}
			});
		} catch (e) {
			this.logger.error(`Could not start watcher: ${e.message}`);
		}
	}

	public parseTransitions() {
		const translations: Record<string, any> = {};

		if (!fs.existsSync(this.options.loadingOptions.path)) {
			this.logger.error(
				`Translations directory not found: ${this.options.loadingOptions.path}`
			);
			return;
		}

		const languages = fs
			.readdirSync(this.options.loadingOptions.path)
			.filter(f => fs.statSync(path.join(this.options.loadingOptions.path, f)).isDirectory());

		for (const lang of languages) {
			const langPath = path.join(this.options.loadingOptions.path, lang);
			translations[lang] = this.readDirectory(langPath);
		}

		if (this.options.generatedTypesPath) {
			this.generateTypes(translations);
		}

		return translations;
	}

	private readDirectory(dirPath: string): Record<string, any> {
		const result: Record<string, any> = {};
		const files = fs.readdirSync(dirPath);

		for (const file of files) {
			const fullPath = path.join(dirPath, file);
			const stat = fs.statSync(fullPath);

			if (stat.isDirectory() && this.options.loadingOptions.enableSubfolders) {
				result[file] = this.readDirectory(fullPath);
			} else if (stat.isFile() && file.endsWith('.json')) {
				const ns = path.parse(file).name;
				try {
					const content = fs.readFileSync(fullPath, 'utf-8');
					result[ns] = JSON.parse(content);
				} catch (e) {
					this.logger.warn(`Failed to parse JSON at ${fullPath}, skipping this file`);
				}
			}
		}
		return result;
	}

	private generateTypes(translations: Record<string, any>) {
		const outputPath = this.options.generatedTypesPath;
		if (!outputPath) return;

		this.logger.log(`Checking transition types changes...`);

		const schema = translations[this.options.fallbackLanguage];

		const fileContent = `/* STOP!!! DO NOT EDIT, file generated by nestjs-i18next */

/* eslint-disable */
/* prettier-ignore */
export type I18nTranslations = ${this.generateUnionType(schema)};

/* prettier-ignore */
export type I18nPath = I18nTranslations['key'];

/* prettier-ignore */
export type ExtractArgs<P extends I18nPath> = Extract<I18nTranslations, { key: P }> extends { args: infer A }
    ? A
    : never;
`;

		fs.mkdirSync(path.dirname(outputPath), {
			recursive: true
		});

		let currentFileContent: string | null = null;
		try {
			currentFileContent = fs.readFileSync(outputPath, 'utf8');
		} catch (err) {
			this.logger.error(err);
		}

		if (currentFileContent != fileContent) {
			fs.writeFileSync(outputPath, fileContent);
			this.logger.log(`Types generated in: ${outputPath}.
                Please also add it to ignore files of your linter and formatter to avoid linting and formatting it
                `);
		} else {
			this.logger.log('No types changes detected');
		}
	}

	private generateUnionType(obj: any, prefix = ''): string {
		const entries = Object.entries(obj);
		return entries
			.map(([key, value]) => {
				const fullKey = prefix ? `${prefix}.${key}` : key;

				if (typeof value === 'string') {
					const simpleVars = [...value.matchAll(/{{(\w+)}}/g)].map(m => m[1]);
					const icuVars = [...value.matchAll(/{(\w+),\s*plural/g)].map(m => m[1]);
					const allVars = [...new Set([...simpleVars, ...icuVars])];

					if (allVars.length === 0) {
						return `{ key: "${fullKey}" }`;
					}
					const args = allVars.map(v => `"${v}": any`).join(', ');
					return `{ key: "${fullKey}", args: { ${args} } }`;
				}
				return this.generateUnionType(value, fullKey);
			})
			.join('\n    | ');
	}
}
